config/routes.rb
Rails.application.routes.draw do
  resources :surf_spots

  root 'surf_spots#index'

end

app/models/surf_spot.rb
class SurfSpot < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/surf_spots_controller.rb
class SurfSpotsController < ApplicationController

  def new
    @surf_spot = SurfSpot.new
  end

  def create
    @surf_spot = SurfSpot.new(surf_spot_params)

    @surf_spot.save
    redirect_to @surf_spot
  end

  def show
    @surf_spot = SurfSpot.find(params[:id])
  end

  def index
    @surf_spots = SurfSpot.all
  end

  private

    def surf_spot_params
      params.require(:surf_spot).permit(
        :name,
        :description,
        :place,
        :region,
        :country,
        :latitude,
        :longtitude,
        :stoke_rating
      )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/surf_spots_helper.rb
module SurfSpotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoSurf</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/surf_spots/index.html.erb
<h1>Surf Spots</h1>

<% @surf_spots.each do | surf_spot | %>
  <h2> <%= surf_spot.name %> </h2>
  <%= surf_spot.place %>
  <%= surf_spot.region
   %>
  <%= surf_spot.stoke_rating %>
  <%= link_to "Show", surf_spot_path(surf_spot) %>
<% end %>

app/views/surf_spots/new.html.erb
<h1>Add a New Surf Spot</h1>

<%= form_for :surf_spot, url: surf_spots_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </p>

  <p>
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </p>

  <p>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </p>

  <p>
    <%= f.label :latitude %><br>
    <%= f.number_field :latitude, step: :any %>
  </p>

  <p>
    <%= f.label :longtitude %><br>
    <%= f.number_field :longtitude, step: :any %>
  </p>

  <p>
    <%= f.label :stoke_rating %><br>
    <%= f.number_field :stoke_rating %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/surf_spots/show.html.erb
<p>
  <strong>Surf Spot</strong>
  <%= @surf_spot.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @surf_spot.description %>
</p>

<p>
  <strong>Place</strong>
  <%= @surf_spot.place %>
</p>

<p>
  <strong>Region:</strong>
  <%= @surf_spot.region %>
</p>

<p>
  <strong>Country</strong>
  <%= @surf_spot.country %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @surf_spot.latitude %>
</p>

<p>
  <strong>Longtitude</strong>
  <%= @surf_spot.longtitude %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @surf_spot.stoke_rating %>
</p>